package com.liangxun.yuejiula.entity;

import com.liangxun.yuejiula.db.DaoSession;
import com.liangxun.yuejiula.db.SchoolFindDao;
import de.greenrobot.dao.DaoException;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SCHOOL_FIND.
 */
public class SchoolFind {

    /** Not-null value. */
    private String school_find_id;
    private String pic_url;
    private String title;
    private String www_url;
    private String top_num;
    private String istype;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SchoolFindDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SchoolFind() {
    }

    public SchoolFind(String school_find_id) {
        this.school_find_id = school_find_id;
    }

    public SchoolFind(String school_find_id, String pic_url, String title, String www_url, String top_num, String istype) {
        this.school_find_id = school_find_id;
        this.pic_url = pic_url;
        this.title = title;
        this.www_url = www_url;
        this.top_num = top_num;
        this.istype = istype;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSchoolFindDao() : null;
    }

    /** Not-null value. */
    public String getSchool_find_id() {
        return school_find_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSchool_find_id(String school_find_id) {
        this.school_find_id = school_find_id;
    }

    public String getPic_url() {
        return pic_url;
    }

    public void setPic_url(String pic_url) {
        this.pic_url = pic_url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getWww_url() {
        return www_url;
    }

    public void setWww_url(String www_url) {
        this.www_url = www_url;
    }

    public String getTop_num() {
        return top_num;
    }

    public void setTop_num(String top_num) {
        this.top_num = top_num;
    }

    public String getIstype() {
        return istype;
    }

    public void setIstype(String istype) {
        this.istype = istype;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
